name: Code quality

on: pull_request

jobs:
  php_cs_fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.5

      - name: Setup PHP
        uses: shivammathur/setup-php@2.15.0
        with:
          php-version: '8.0'
          tools: composer

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2.1.6
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install

      - name: Run PHP-CS-Fixer
        run: vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.php --verbose --allow-risky=yes --dry-run

  psalm:
    name: Psalm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.5

      - name: Setup PHP
        uses: shivammathur/setup-php@2.15.0
        with:
          php-version: '8.0'
          tools: composer

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2.1.6
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install

      - name: Run Psalm
        run: vendor/bin/psalm --show-info=true --output-format=github

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.5

      - name: Setup PHP
        uses: shivammathur/setup-php@2.15.0
        with:
          php-version: '8.0'
          tools: composer

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2.1.6
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install

      - name: Run PHPStan
        run: vendor/bin/phpstan analyze --configuration=phpstan.neon --error-format=github

  prettier:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.5

      - name: Cache dependencies
        uses: actions/cache@v2.1.6
        with:
          path: ./.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Setup Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '16.x'

      - name: Install npm dependencies
        run: npm ci --prefer-offline --cache=./.npm

      - name: Lint with ESLint
        run: npx prettier --check .
